name: Build DNSCloak tipa

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos

      - name: Build DNSCloak
        run: |
          make THEOS=~/theos

      - name: Package .tipa
        run: |
          mkdir -p Payload
          cp -r obj/DNSCloak.app Payload/
          zip -r DNSCloak.tipa Payload

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: DNSCloak.tipa
          path: DNSCloak.tipa
